# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build Artifact

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '.github/workflows/Release.yml'
      - 'LICENSE'
      - 'README.md'
  pull_request:
    paths-ignore:
      - '.github/workflows/Release.yml'
      - 'LICENSE'
      - 'README.md'
  workflow_dispatch:
  
permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: gradle # Only cache stuff since test build action happen mostly

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        # A file, directory or wildcard pattern that describes what to upload
        path: build/libs/*.jar
